json.id @instance.id
json.phone_number @instance.phone_number
json.fullname @instance.fullname
json.nickname @instance.nickname
json.active @instance.active
json.created_at @instance.created_at
json.updated_at @instance.updated_at
json.url api_person_url(@instance)
json.response_count 0
json.call_count 0
json.situations []
